POST http://localhost:3000/memories
Content-Type: multipart/form-data; boundary=----1234567890
Content-Length: auto

------1234567890
Content-Disposition: form-data; name="title"

cachorro
------1234567890
Content-Disposition: form-data; name="description"

Uma imagem de um cachorro
------1234567890
Content-Disposition: form-data; name="image"; filename="dogandcat.png"
Content-Type: image/png

< C:\Users\win10\Downloads\dogandcat.png
------1234567890--

###
# GET ALL
GET http://localhost:3000/memories

###
# GET INDIVIDUAL
GET http://localhost:3000/memories/677549345e41208dd127562c

###
DELETE http://localhost:3000/memories/677549345e41208dd127562c

###
# FAVORITE
PATCH http://localhost:3000/memories/favorite/677549ce5e41208dd1275638



### 
# UPDATE
PATCH http://localhost:3000/memories/677549ce5e41208dd1275638
Content-Type: multipart/form-data; boundary=----1234567890
Content-Length: auto

------1234567890
Content-Disposition: form-data; name="title"

UM CACHORRO E UM GATO
------1234567890
Content-Disposition: form-data; name="description"

Outra imagem de um outro cachorro

------1234567890
Content-Disposition: form-data; name="image"; filename="dogandcat.png"
Content-Type: image/png

< C:\Users\win10\Downloads\dogandcat.png
------1234567890--

###
# COMMENT
PATCH http://localhost:3000/memories/677549ce5e41208dd1275638/comment
Content-Type: application/json

{
    "name": "Jhonatan",
    "text": "Primeiro comentário"
}