# SERVIÇOS

POST http://localhost:3000/api/services
Content-Type: application/json

{
        "name": "Decoração",
        "description": "Escolha a decoração para sua festa, e nós a montamos.",
        "price": 1400,
        "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
    }

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6765f0285c847bd1788ec1bd
###
DELETE http://localhost:3000/api/services/6766ccafe1ef3f34fbee903f

###
PUT http://localhost:3000/api/services/6766d1956df638a10af1ae22
Content-Type: application/json

{
    "name" : "TESTE ATUALIZAÇÃO",
    "description":"Alguma descricao",
    "price": 2500,
    "image": "https://images.unsplash.com/photo-1730829807423-83b045bd6cfd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}


# FESTAS
### 
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento Manual 2",
    "author": "Jhonatan",
    "description": "Uma festa de aniversário",
    "budget": 5000,
    "image": "https://images.unsplash.com/photo-1730829807423-83b045bd6cfd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
    {
        "name" : "Algum serviço 1",
        "description":"Alguma descricao",
        "price": 1000,
        "image": "https://images.unsplash.com/photo-1730829807423-83b045bd6cfd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    }
]
}

###
# GETALL
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/6769d684e2653acf045d7353

###
DELETE http://localhost:3000/api/parties/676c3b805b6339448fe4825a

###
PUT http://localhost:3000/api/parties/6769d684e2653acf045d7353
Content-Type: application/json

{
    "title": "Meu evento 2",
    "author": "Jhonatan",
    "description": "Uma festa de aniversário",
    "budget": 3000,
    "image": "https://images.unsplash.com/photo-1730829807423-83b045bd6cfd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
    {
        "name" : "Algum serviço 1",
        "description":"Alguma descricao",
        "price": 1000,
        "image": "https://images.unsplash.com/photo-1730829807423-83b045bd6cfd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        "name" : "Algum serviço 2",
        "description":"Alguma descricao",
        "price": 1000,
        "image": "https://images.unsplash.com/photo-1730829807423-83b045bd6cfd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        "name" : "Algum serviço 3",
        "description":"Alguma descricao",
        "price": 1000,
        "image": "https://images.unsplash.com/photo-1730829807423-83b045bd6cfd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    }
    ]
}